kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# Remote base.  Use the configuration from the Red Hat Canada GitOps repo (unofficial).
bases:
  - overlays/default

patches:
-  target:
     kind: AutomationController
     name: tower
   patch: |-
    - op: add
      path: /spec/postgres_storage_class
      value: 'ocs-storagecluster-cephfs'