apiVersion: batch/v1
kind: Job
metadata:
  name: acm-observability-preinstall
  annotations:
    argocd.argoproj.io/sync-wave: "201"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    gitops.tier.group: rhacm
    gitops.tier.layer: services
  namespace: open-cluster-management-observability 
spec:
  template:
    spec:
      containers:
      - name: acm-observability-preinstall
        image: quay.io/benswinneyau/acm-observability-pre-install:0.1
        imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 2