apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: "acm-observability-obc"
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    argocd.argoproj.io/hook: PreSync
spec:
  generateBucketName: "acm.observability"
  storageClassName: openshift-storage.noobaa.io